# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Lists available commands
    cmds:
      - task -l
  list:
    desc: Lists available commands
    cmds:
      - task -l
  tidy:
    desc: Downloads dependencies and removes unused ones
    cmds:
      - go mod tidy
  fmt:
    desc: Lint code
    cmds:
      - go fmt ./...

  generate:
    desc: Runs all //go:generate commands embedded in .go files
    cmds:
      - go generate ./...

  install:tools:
    desc: Install all optional cli tools
    dir: scripts
    cmds:
      - task: install:golangci
      - task: install:swagger
      - task: install:goose
      - task: install:mirip
      - task: install:buf
    silent: true

  swagger:
    desc: Generates Swagger page for API reference
    cmds:
      - swag init -g cmd/server/main.go

  buf:
    desc: Buf gen
    cmds:
      - buf generate
  install:golangci:
    desc: Install golangci linter
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

  install:swagger:
    desc: Install swagger cli
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest

  install:buf:
    desc: Install buf cli
    cmds:
      - go install github.com/bufbuild/buf/cmd/buf@v1.13.1

  install:mirip:
    desc: Install mock generator
    cmds:
      - go install github.com/gmhafiz/mirip/cmd/mirip@latest

  install:goose:
    desc: Install golang migration tool
    cmds:
      - go install github.com/pressly/goose/v3/cmd/goose@latest
